CREATE TABLE recipes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  rec_description TEXT,
  servings INTEGER,
  preptime INTEGER,
  cooktime INTEGER,
  ingredients TEXT,
  instructions TEXT,
  notes TEXT
);